"""
Default configuration file
"""

import torch
import numpy as np


class Config:
    """Base configuration class"""
    
    # Device configuration
    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
    
    # Network configuration
    NETWORK_TYPE = 'ws'         # Network type: 'ws' (Watts-Strogatz) or 'fc' (Fully Connected)
    N_OSCILLATORS = 100         # Number of oscillators N
    K_NEIGHBORS = 4             # nearest neighbors k (WS network only)
    REWIRING_PROB = 0.1         # rewiring probability p (WS network only)
    
    # Natural-frequency configuration
    NATURAL_FREQ_STD = 0.1      # standard deviation of the Gaussian natural-frequency distribution σ
    
    # Model configuration
    CONTEXT_LENGTH = 20         # history window length T
    D_MODEL = 32                # feature dimension d
    COUPLING_STRENGTH = 1.0     # Coupling strength λ
    NOISE_STRENGTH = 0.05       # noise strength D
    
    # Alpha configuration
    LEARNABLE_ALPHA = True      # whether to train alpha (False means fixed)
    ALPHA_INIT = 0.0            # initial alpha value (actual alpha=sigmoid(ALPHA_INIT))
    # Tip: IfLEARNABLE_ALPHA=Falseand needalpha≈1, setALPHA_INIT=5.0 (sigmoid(5)≈0.99)
    
    # Training configuration
    TASK = 'sync'               # Task type: 'sync' or 'desync' (control objective)
    ATTENTION_TYPE = 'neighbor' # attention type: 'neighbor' (Â=A) or 'self' (Â=I)
    N_EPOCHS = 100              # number of training epochs
    N_EPISODES_PER_EPOCH = 10  # episodes per epoch
    N_VAL_EPISODES = 5          # validation episodes
    N_STEPS = 200               # simulation steps per episode（time-varying history window）
    LEARNING_RATE = 1e-3        # learning rate
    
    # Save configuration（generated by property，includes network type）
    @property
    def SAVE_DIR(self):
        return f'./results/{self.TASK}_{self.ATTENTION_TYPE}_{self.NETWORK_TYPE}'
    
    @classmethod
    def to_dict(cls):
        """Convert to dictionary"""
        return {
            k: v for k, v in cls.__dict__.items() 
            if not k.startswith('_') and not callable(v)
        }
    
    @classmethod
    def print_config(cls):
        """Print configuration"""
        print("=" * 50)
        print("Configuration")
        print("=" * 50)
        for k, v in cls.to_dict().items():
            print(f"{k}: {v}")
        print("=" * 50)


class SyncConfig(Config):
    """Synchronization task configuration"""
    TASK = 'sync'
    ATTENTION_TYPE = 'neighbor'
    COUPLING_STRENGTH = 2.0
    ALPHA_INIT = 0.0
    
    @property
    def SAVE_DIR(self):
        return f'./results/sync_neighbor_{self.NETWORK_TYPE}'


class SyncSelfConfig(Config):
    """Synchronization task + self-DTA"""
    TASK = 'sync'
    ATTENTION_TYPE = 'self'
    COUPLING_STRENGTH = 2.0
    ALPHA_INIT = 0.0
    
    @property
    def SAVE_DIR(self):
        return f'./results/sync_self_{self.NETWORK_TYPE}'


class DesyncConfig(Config):
    """Desynchronization task configuration"""
    TASK = 'desync'
    ATTENTION_TYPE = 'self'
    COUPLING_STRENGTH = 2.0
    ALPHA_INIT = 0.0
    
    @property
    def SAVE_DIR(self):
        return f'./results/desync_self_{self.NETWORK_TYPE}'


class DesyncNeighborConfig(Config):
    """Desynchronization task + neighbor-DTA"""
    TASK = 'desync'
    ATTENTION_TYPE = 'neighbor'
    COUPLING_STRENGTH = 2.0
    ALPHA_INIT = 0.0
    
    @property
    def SAVE_DIR(self):
        return f'./results/desync_neighbor_{self.NETWORK_TYPE}'


class TestConfig(Config):
    """Test configuration (small quick test)"""
    N_OSCILLATORS = 20
    CONTEXT_LENGTH = None  # time-varying history window，no preset required
    N_EPOCHS = 20
    N_EPISODES_PER_EPOCH = 5
    N_VAL_EPISODES = 3
    N_STEPS = 300  # increased to 300 steps
    
    @property
    def SAVE_DIR(self):
        return f'./results/test_{self.NETWORK_TYPE}'
